apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: pfsense-disk-dv
  namespace: fallilou-dev
spec:
  source:
    blank: {}
  storage:
    storageClassName: gp3
    resources:
      requests:
        storage: 20Gi
    accessModes:
      - ReadWriteOnce
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: pfsense-iso-dv
  namespace: fallilou-dev
spec:
  source:
    http:
      url: "https://atxfiles.netgate.com/mirror/downloads/pfSense-CE-2.7.2-RELEASE-amd64.iso.gz"
  storage:
    storageClassName: gp3
    resources:
      requests:
        storage: 5Gi
    accessModes:
      - ReadWriteOnce
