---
# =====================================================
# VM1 — pfSense Firewall
# Adapté Sandbox : 1 seule interface (pod network)
# NAD DMZ/LAN non disponibles sur ce Sandbox
# Les règles firewall sont documentées dans firewall-rules.xml
# =====================================================
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm1-pfsense
  namespace: fallilou-dev
  labels:
    kubevirt.io/domain: vm1-pfsense
    app: vm1-pfsense
    zone: wan
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1-pfsense
        app: vm1-pfsense
        zone: wan
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 1Gi
        resources:
          requests:
            memory: 1Gi
            cpu: "500m"
          limits:
            memory: 1Gi
            cpu: "2"
        devices:
          disks:
            - name: pfsense-disk
              disk:
                bus: virtio
              bootOrder: 1
            - name: pfsense-iso
              cdrom:
                bus: sata
                readonly: true
              bootOrder: 2
          interfaces:
            # Interface WAN uniquement (pod network = NAT Internet)
            - name: wan
              masquerade: {}
              model: virtio
          rng: {}
      networks:
        - name: wan
          pod: {}
      volumes:
        - name: pfsense-disk
          dataVolume:
            name: pfsense-disk-dv
        - name: pfsense-iso
          dataVolume:
            name: pfsense-iso-dv

---
# Disque système pfSense (20Gi, gp3)
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: pfsense-disk-dv
  namespace: fallilou-dev
spec:
  source:
    blank: {}
  storage:
    storageClassName: gp3
    resources:
      requests:
        storage: 20Gi
    accessModes:
      - ReadWriteOnce

---
# Import ISO pfSense CE 2.7
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: pfsense-iso-dv
  namespace: fallilou-dev
spec:
  source:
    http:
      url: "https://atxfiles.netgate.com/mirror/downloads/pfSense-CE-2.7.2-RELEASE-amd64.iso.gz"
  storage:
    storageClassName: gp3
    resources:
      requests:
        storage: 5Gi
    accessModes:
      - ReadWriteOnce
