apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm1-pfsense
  namespace: fallilou-dev
  labels:
    kubevirt.io/domain: vm1-pfsense
    app: vm1-pfsense
spec:
  runStrategy: Manual
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: vm1-pfsense-rootdisk
      spec:
        source:
          blank: {}
        storage:
          storageClassName: gp3
          resources:
            requests:
              storage: 10Gi
          accessModes:
            - ReadWriteOnce
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1-pfsense
        app: vm1-pfsense
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        memory:
          guest: 1Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
          rng: {}
        machine:
          type: pc-q35-rhel9.2.0
        firmware:
          bootloader:
            efi: {}
        features:
          smm:
            enabled: true
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          dataVolume:
            name: vm1-pfsense-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm1-pfsense
              user: admin
              password: pfsense
              chpasswd: { expire: False }
