apiVersion: v1
kind: ConfigMap
metadata:
  name: vm3-db-initdb
  namespace: fallilou-dev
data:
  01-init.sql: |
    CREATE DATABASE IF NOT EXISTS appdb
      CHARACTER SET utf8mb4
      COLLATE utf8mb4_unicode_ci;

    CREATE USER IF NOT EXISTS 'appuser'@'%'
      IDENTIFIED BY 'AppPassword123x';

    GRANT ALL PRIVILEGES ON appdb.* TO 'appuser'@'%';

    FLUSH PRIVILEGES;

    USE appdb;

    CREATE TABLE IF NOT EXISTS etudiants (
      id        INT AUTO_INCREMENT PRIMARY KEY,
      nom       VARCHAR(100) NOT NULL,
      prenom    VARCHAR(100) NOT NULL,
      email     VARCHAR(150) UNIQUE,
      filiere   VARCHAR(100),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT IGNORE INTO etudiants (nom, prenom, email, filiere) VALUES
      ('Diallo',  'Mamadou',  'mamadou@univ.sn',  'Informatique'),
      ('Sow',     'Fatou',    'fatou@univ.sn',    'Réseaux'),
      ('Ndiaye',  'Ibrahima', 'ibrahima@univ.sn', 'Cloud'),
      ('Ba',      'Aissatou', 'aissatou@univ.sn', 'Cybersécurité'),
      ('Fall',    'Cheikh',   'cheikh@univ.sn',   'DevOps'),
      ('Diop',    'Mariama',  'mariama@univ.sn',  'Informatique'),
      ('Kane',    'Ousmane',  'ousmane@univ.sn',  'Réseaux');

    CREATE TABLE IF NOT EXISTS cours (
      id          INT AUTO_INCREMENT PRIMARY KEY,
      titre       VARCHAR(200) NOT NULL,
      description TEXT,
      credits     INT DEFAULT 3,
      created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT IGNORE INTO cours (titre, description, credits) VALUES
      ('Virtualisation',     'OpenShift, KubeVirt, VMware',    4),
      ('Réseaux avancés',    'BGP, OSPF, SDN, pfSense',        4),
      ('Cloud Computing',    'AWS, Azure, OpenShift',          3),
      ('Cybersécurité',      'Firewall, IDS, VPN, iptables',   4),
      ('DevOps',             'CI/CD, GitHub Actions, Docker',  3);
