apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm3-mysql-data
  namespace: projet-fin-module
  labels:
    app: vm3-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
