apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm3-mysql-data
  namespace: fallilou-dev
  labels:
    app: vm3-db
    zone: lan
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
