apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm3-db
  namespace: fallilou-dev
  labels:
    kubevirt.io/domain: vm3-db
    app: vm3-db
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm3-db
        app: vm3-db
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 2Gi
        resources:
          requests:
            memory: 2Gi
            cpu: "500m"
          limits:
            memory: 2Gi
            cpu: "2"
        devices:
          disks:
            - name: ubuntu-disk
              disk:
                bus: virtio
              bootOrder: 1
            - name: cloudinit-disk
              disk:
                bus: virtio
          interfaces:
            - name: pod-network
              masquerade: {}
              model: virtio
          rng: {}
      networks:
        - name: pod-network
          pod: {}
      volumes:
        - name: cloudinit-disk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm3-db
              timezone: Africa/Dakar
              users:
                - name: ubuntu
                  groups: sudo
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  shell: /bin/bash
                  lock_passwd: false
                  passwd: $6$CT.OxNzznZS8fra/$OqQufVTTaBPSiJ1x8/I9XaWIQyBV4cobZtZymtJy.T04CkuRyEe6dv7ohRupWYARQM3YSc/qvF3iKFbC/FNgC1
              ssh_pwauth: true
              package_update: true
              packages:
                - mysql-server
                - ufw
              write_files:
                - path: /etc/mysql/mysql.conf.d/99-projet.cnf
                  permissions: '0644'
                  content: |
                    [mysqld]
                    bind-address = 0.0.0.0
                - path: /opt/mysql-init.sql
                  permissions: '0600'
                  content: |
                    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'RootPassword123!';
                    CREATE DATABASE IF NOT EXISTS appdb CHARACTER SET utf8mb4;
                    CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED WITH mysql_native_password BY 'AppPassword123!';
                    GRANT ALL PRIVILEGES ON appdb.* TO 'appuser'@'%';
                    FLUSH PRIVILEGES;
              runcmd:
                - systemctl start mysql
                - mysql -u root < /opt/mysql-init.sql
                - rm -f /opt/mysql-init.sql
                - systemctl enable mysql
                - ufw allow 22/tcp
                - ufw allow 3306/tcp
                - ufw --force enable
              final_message: "VM3 DB prete !"
        - name: ubuntu-disk
          dataVolume:
            name: vm3-ubuntu-dv
