apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: vm2-ubuntu-dv
  namespace: fallilou-dev
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
  storage:
    storageClassName: gp3
    resources:
      requests:
        storage: 20Gi
    accessModes:
      - ReadWriteOnce
