apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm2-web
  namespace: fallilou-dev
  labels:
    kubevirt.io/domain: vm2-web
    app: vm2-web
    zone: dmz
spec:
  runStrategy: Manual
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: vm2-web-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          storageClassName: gp3
          resources:
            requests:
              storage: 20Gi
          accessModes:
            - ReadWriteOnce
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm2-web
        app: vm2-web
        zone: dmz
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        memory:
          guest: 1Gi
        resources:
          requests:
            memory: 1Gi
            cpu: "250m"
          limits:
            memory: 1Gi
            cpu: "500m"
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
          rng: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          dataVolume:
            name: vm2-web-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm2-web
              user: fedora
              password: Fedora2024x
              chpasswd: { expire: False }
              ssh_pwauth: true
              packages:
                - nginx
                - nodejs
                - npm
              runcmd:
                - mkdir -p /opt/app
                - echo '{"name":"app","version":"1.0.0","dependencies":{"express":"^4.18.2","mysql2":"^3.6.0"}}' > /opt/app/package.json
                - echo 'const e=require("express"),a=e(),P=3000;a.get("/",(q,r)=>r.json({status:"OK",vm:"vm2-web",zone:"DMZ"}));a.get("/health",(q,r)=>r.json({status:"UP"}));a.listen(P)' > /opt/app/index.js
                - cd /opt/app && npm install
                - systemctl enable nginx
                - systemctl start nginx
