apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm1-firewall
  namespace: fallilou-dev
  labels:
    kubevirt.io/domain: vm1-firewall
    app: vm1-firewall
    zone: wan
spec:
  runStrategy: Manual
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: vm1-firewall-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          storageClassName: gp3
          resources:
            requests:
              storage: 32Gi
          accessModes:
            - ReadWriteOnce
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1-firewall
        app: vm1-firewall
        zone: wan
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        memory:
          guest: 512Mi
        resources:
          requests:
            memory: 512Mi
            cpu: "250m"
          limits:
            memory: 512Mi
            cpu: "500m"
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
          rng: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          dataVolume:
            name: vm1-firewall-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm1-firewall
              user: fedora
              password: Fedora2024x
              chpasswd: { expire: False }
              ssh_pwauth: true
              packages:
                - iptables
                - iptables-services
                - iproute
              runcmd:
                - echo 1 > /proc/sys/net/ipv4/ip_forward 
                - ip link add dmz0 type dummy || true
                - ip addr add 192.168.100.1/24 dev dmz0 || true
                - ip link set dmz0 up
                - ip link add lan0 type dummy || true
                - ip addr add 192.168.10.1/24 dev lan0 || true
                - ip link set lan0 up
                - iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
                - iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
                - iptables -A FORWARD -i eth0 -o dmz0 -p tcp -m multiport --dports 80,443 -j ACCEPT
                - iptables -A FORWARD -i eth0 -o lan0 -j DROP
                - iptables -A FORWARD -i lan0 -o eth0 -j ACCEPT
                - iptables -A FORWARD -i lan0 -o dmz0 -j ACCEPT
                - iptables -A FORWARD -i dmz0 -o lan0 -j DROP
                - iptables -A FORWARD -i dmz0 -o eth0 -p tcp -m multiport --dports 80,443 -j ACCEPT
                - iptables -P FORWARD DROP
                - service iptables save || true
