apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm1-firewall
  namespace: fallilou-dev
  labels:
    kubevirt.io/domain: vm1-firewall
    app: vm1-firewall
    zone: wan
spec:
  runStrategy: Manual
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: vm1-firewall-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          storageClassName: gp3
          resources:
            requests:
              storage: 32Gi
          accessModes:
            - ReadWriteOnce
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1-firewall
        app: vm1-firewall
        zone: wan
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        memory:
          guest: 512Mi
        resources:
          requests:
            memory: 512Mi
            cpu: "250m"
          limits:
            memory: 512Mi
            cpu: "500m"
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
          rng: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          dataVolume:
            name: vm1-firewall-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataSecretRef:
              name: vm1-firewall-cloudinit
